services:
    # Database service
    # Use PostgreSQL as the database backend
    db:
        image: postgres:17
        container_name: inventree-db
        restart: unless-stopped
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdb
            - POSTGRES_USER=${INVENTREE_DB_USER:?}
            - POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?}
            - POSTGRES_DB=${INVENTREE_DB_NAME:?}
            - TZ=${INVENTREE_TIMEZONE:-Etc/UTC}
        networks:
            - inventree
        volumes:
            # Map 'data' volume such that postgres database is stored externally
            - ${INVENTREE_DB_VOLUME:?}:/var/lib/postgresql/data/:z

    # redis acts as database cache manager
    cache:
        image: valkey/valkey:8.1.2-alpine
        container_name: inventree-cache
        env_file:
            - .env
        networks:
            - inventree
        restart: always

    # InvenTree web server service
    # Uses gunicorn as the web server
    server:
        # https://hub.docker.com/r/inventree/inventree
        build:
            context: .
            dockerfile: Dockerfile
            args:
                INVENTREE_TAG: ${INVENTREE_TAG:-stable}
        image: znibb/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-server
        restart: unless-stopped
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.services.inventree.loadbalancer.server.port=8000

            # Router for KiCad plugin
            - traefik.http.routers.inventree-kicad.rule=Host(`parts.${TRAEFIK_DOMAIN:?}`) && PathPrefix(`/plugin/kicad-library-plugin`)
            - traefik.http.routers.inventree-kicad.priority=200
            - traefik.http.routers.inventree-kicad.entrypoints=websecure
            - traefik.http.routers.inventree-kicad.service=inventree

            # Router for API
            - traefik.http.routers.inventree-api.rule=Host(`parts.${TRAEFIK_DOMAIN:?}`) && PathPrefix(`/api`)
            - traefik.http.routers.inventree-api.priority=200
            - traefik.http.routers.inventree-api.entrypoints=websecure
            - traefik.http.routers.inventree-api.service=inventree

            # Default router
            - traefik.http.routers.inventree.rule=Host(`parts.${TRAEFIK_DOMAIN:?}`)
            - traefik.http.routers.inventree.priority=100
            - traefik.http.routers.inventree.entrypoints=websecure
            - traefik.http.routers.inventree.middlewares=authentik@file
            - traefik.http.routers.inventree.service=inventree
        networks:
            - inventree
            - traefik
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_DATA_VOLUME}:/home/inventree/data:z
        depends_on:
            - db
            - cache

    # Background worker process handles long-running or periodic tasks
    worker:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                INVENTREE_TAG: ${INVENTREE_TAG:-stable}
        image: znibb/inventree:${INVENTREE_TAG:-stable}
        container_name: inventree-worker
        command: invoke worker
        depends_on:
            - server
        env_file:
            - .env
        networks:
            - inventree
        volumes:
            # Data volume must map to /home/inventree/data
            - ${INVENTREE_DATA_VOLUME}:/home/inventree/data:z
        restart: unless-stopped

    # caddy acts as reverse proxy and static file server
    # https://hub.docker.com/_/caddy
    proxy:
        container_name: inventree-proxy
        image: caddy:alpine
        restart: always
        depends_on:
            - server
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.services.inventree-caddy.loadbalancer.server.port=80
            - traefik.http.routers.inventree-media.rule=Host(`parts.${TRAEFIK_DOMAIN:?}`) && PathPrefix(`/media`)
            - traefik.http.routers.inventree-media.priority=200
            - traefik.http.routers.inventree-media.entrypoints=websecure
            - traefik.http.routers.inventree-media.middlewares=authentik@file
            - traefik.http.routers.inventree-media.service=inventree-caddy
        networks:
            - inventree
            - traefik
        volumes:
            - ./files/Caddyfile:/etc/caddy/Caddyfile:ro,z
            - ${INVENTREE_DATA_VOLUME}/static:/var/www/static:z
            - ${INVENTREE_DATA_VOLUME}/media:/var/www/media:z
            - ${INVENTREE_DATA_VOLUME}:/var/log:z
            - ${INVENTREE_DATA_VOLUME}:/data:z
            - ${INVENTREE_DATA_VOLUME}:/config:z

networks:
    inventree:
        name: inventree
    traefik:
        external: true
